---

clusters:
  - name: cluster1
    host: 127.0.0.1
    user: pvecontrol@pve
    timeout: 60
    # password: somerandomsecret
    # token_name: mytokenname
    # token_value: somemorerandomsecret

node:
  cpufactor: 2.5
  memoryminimum: 81928589934592

vm:
  max_last_backup: 1500
