name: Plumber

on:
  push:
    branches: [main]
  pull_request: null

permissions:
  contents: read
  security-events: write
  # id-token: write          # uncomment to publish a live Plumber Score badge (see below)

jobs:
  plumber:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: getplumber/plumber@de6c889e24c9147baa064db656b71c8e98595d15 # pinned plumber version: v0.5.8
        with:
          min-score: "A"
          score-push: false # set to "true" to publish a public Plumber Score badge

